# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - 8080:8080
